version: '2'

services:
  web:
    build: .
    command: bundle exec puma -C config/puma.rb
    image: '536335609904.dkr.ecr.us-east-2.amazonaws.com/connecpath-admin' 
    ports:
      - 80:3000
    environment:
      - chatbot_host=http://chatconnecpath.tk/
      - notification_host=http://notificationconnecpath.tk/
      - manager_host=http://managerconnecpath.tk/
      - SECRET_KEY_BASE=0ff4c99a2dede340ee89a19296d6daf731e5624e8c1566c00e8242a59ef6ce20588a762f037da53620aaac50a15e8c24ad7f5edcc273f02035b365af54224c71
      - ELASTICSEARCH_URL=https://search-connecpath-local-rjb5cihhxyqjuyvqbw7kbm6o3q.us-east-2.es.amazonaws.com
      - RAILS_ENV=production
  sidekiq:
    image: '536335609904.dkr.ecr.us-east-2.amazonaws.com/connecpath-admin'
    command: bundle exec sidekiq -C /usr/src/app/config/sidekiq.yml
