defaults: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
development:
  <<: *default
  
test:
  <<: *default

staging:
  <<: *default
  database: geniusdb
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  username: geniusdb
  password: geniusdb

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  port: 5432
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
