defaults: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>
development:
  <<: *default
  
test:
  <<: *default

staging:
  <<: *default
  database: docgenius_stage
  pool: 5
  host: <%= ENV['db_staging_host']
  port: 5432
  username: docgenius
  password: docgenius

production:
  <<: *default
  database: docgenius_prod
  pool: 5
  host: <%= ENV['db_prod_host']
  port: 5432
  username: docgenius
  password: docgenius
